import { ProfileType } from "../enums/profileType";
import type { Profile } from "../schemas/profile";

export const defaultBots: Array<Profile> = [
    {
        id: 1,
        type: ProfileType.DARTBOT,
        name: "Dartbot 1",
        average: 33,
        checkout: 2,
    },
    {
        id: 2,
        type: ProfileType.DARTBOT,
        name: "Dartbot 2",
        average: 36,
        checkout: 4,
    },
    {
        id: 3,
        type: ProfileType.DARTBOT,
        name: "Dartbot 3",
        average: 41,
        checkout: 6,
    },
    {
        id: 4,
        type: ProfileType.DARTBOT,
        name: "Dartbot 4",
        average: 45,
        checkout: 9,
    },
    {
        id: 5,
        type: ProfileType.DARTBOT,
        name: "Dartbot 5",
        average: 50,
        checkout: 11,
    },
    {
        id: 6,
        type: ProfileType.DARTBOT,
        name: "Dartbot 6",
        average: 55,
        checkout: 15,
    },
    {
        id: 7,
        type: ProfileType.DARTBOT,
        name: "Dartbot 7",
        average: 60,
        checkout: 19,
    },
    {
        id: 8,
        type: ProfileType.DARTBOT,
        name: "Dartbot 8",
        average: 65,
        checkout: 23,
    },
    {
        id: 9,
        type: ProfileType.DARTBOT,
        name: "Dartbot 9",
        average: 70,
        checkout: 27,
    },
    {
        id: 10,
        type: ProfileType.DARTBOT,
        name: "Dartbot 10",
        average: 75,
        checkout: 30,
    },
    {
        id: 11,
        type: ProfileType.DARTBOT,
        name: "Dartbot 11",
        average: 80,
        checkout: 35,
    },
    {
        id: 12,
        type: ProfileType.DARTBOT,
        name: "Dartbot 12",
        average: 85,
        checkout: 40,
    },
    {
        id: 13,
        type: ProfileType.DARTBOT,
        name: "Dartbot 13",
        average: 90,
        checkout: 45,
    },
    {
        id: 14,
        type: ProfileType.DARTBOT,
        name: "Dartbot 14",
        average: 95,
        checkout: 50,
    },
    {
        id: 15,
        type: ProfileType.DARTBOT,
        name: "Dartbot 15",
        average: 100,
        checkout: 55,
    },
    {
        id: 16,
        type: ProfileType.DARTBOT,
        name: "Dartbot 16",
        average: 105,
        checkout: 60,
    },
    {
        id: 17,
        type: ProfileType.DARTBOT,
        name: "Dartbot 17",
        average: 110,
        checkout: 65,
    },
    {
        id: 18,
        type: ProfileType.DARTBOT,
        name: "Dartbot 18",
        average: 115,
        checkout: 70,
    },
    {
        id: 19,
        type: ProfileType.DARTBOT,
        name: "Dartbot 19",
        average: 120,
        checkout: 75,
    },
    {
        id: 20,
        type: ProfileType.DARTBOT,
        name: "Dartbot 20",
        average: 125,
        checkout: 80,
    },
];
